### ISSUE TITLE
build gold foot print mask in healsparse

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter-masking#2]
For this mask, we want to record the set of healpix pixels defined as in gold according to the table `CARNERO.Y6A2_FOOTPRINT_GRIZ_N2_ALLCOLUMNS` in desci in healsparse. The healsparse mask should have a value of 1 for regions in the survey and no bits set outside. 

Let's use nside 131072

**Comment by esheldon** [comment]
Why higher nside?

**Comment by esheldon** [comment]
I found a problem with that table; Aurelio is going to remake it

**Comment by beckermr** [comment]
thank you!

**Comment by esheldon** [comment]
I updated the first comment to show the new table name

**Comment by beckermr** [comment]
We don't have to use the higher inside. I actually make the metadetection healsparse masks at this nside.

**Comment by esheldon** [comment]
So all we have is 4096 from gold footprint

Eli pointed out that there isn't a point in upsampling it.  We can just check against it.  This is in the apply_masks.py that I just pushed.

**Comment by beckermr** [comment]
We want the actual mask so people can use it for power spectra. Checking it against a catalog is secondary.

**Comment by esheldon** [comment]
Yes, I need this function to create the combined footprint.
