### ISSUE TITLE
compute final mask for catalog

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter-masking#5]
The final mask for the catalog is where

(metadetect mask == 1) & (foreground mask == 0) and (footprint mask == 1)

This should be fairly easily computable in healsparse. 

This mask can be written out in some format, say 1 where things are in the mask and zero otherwise or w/e.

**Comment by esheldon** [comment]
There is no way in healsparse to upsample a map.  So our footprint is in 4096, the mask is 16384 and mdet will be whatever it is.

I've put code in apply_masks.py to apply these to a set of ra dec as three separate steps rather than combining them.

**Comment by esheldon** [comment]
I think the way to make a combined map is to generate a full sky healpy map at 16384 and check all its ra, dec using the above code and then make a new healsparse map based on that.

**Comment by esheldon** [comment]
(will need to degrade the metadetect footprint to 16384 for this)

**Comment by beckermr** [comment]
It should be easy to produce an up sampled foot print map using bit shifts. It should be two bits left and then add 0, 1, 2, 3 to get the new indices for a single change in resolution

**Comment by esheldon** [comment]
But there is no need.  I can do it as I described.

**Comment by beckermr** [comment]
Ok w/e works!
