### ISSUE TITLE
get info from Eli how he produced gold_2_0_r_lt_21_summary.fit

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter-masking#7]

**Comment by esheldon** [comment]
@erykoff I merged that other PR, let's discuss the provenance of the file here

**Comment by beckermr** [comment]
@erykoff any comments here?

**Comment by erykoff** [comment]
This is from my download of y6a1 gold 2.0, though there is a possibility I messed up the mask there which is unfortunate.  Then this:
```
    ok, = np.where(bdf['flux_bdf_r'] > 0.0)
    r_mag = 30.0 - 2.5*np.log10(bdf['flux_bdf_r'][ok])
```
